---
- hosts: all
  become: yes
  vars:

  roles:
    - 1f618.circuitpython_on_linux

  tasks:
    - name: "Update hostname."
      hostname:
        name: "rpi-eink-weather"

    - name: "apt update, apt upgrade"
      # https://stackoverflow.com/a/41537418
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400  # One day

    # https://learn.adafruit.com/raspberry-pi-e-ink-weather-station-using-python/python-setup

