---
- hosts: all
  become: yes
  vars:
    pip_install_packages:
      - name: adafruit-circuitpython-epd
    eink_project_name: EInk_Bonnet_Weather_Station
    eink_dir: "/home/pi/{{ eink_project_name }}"

  roles:
    - 1f618.circuitpython_on_linux

  tasks:
    - name: "Update hostname."
      hostname:
        name: "rpi-eink-weather"

    - name: "apt update, apt upgrade"
      # https://stackoverflow.com/a/41537418
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400  # One day

    # https://learn.adafruit.com/raspberry-pi-e-ink-weather-station-using-python/python-setup

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - fonts-dejavu
        - python3-pil

    - name: "Create {{ eink_dir }} directory"
      ansible.builtin.file:
        path: "{{ eink_dir }}"
        state: directory

    - name: "Download {{ eink_project_name }} project files"
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ eink_dir }}/{{ item.name }}"
      with_items:
        - name: meteocons.ttf
          url: https://github.com/adafruit/Adafruit_Learning_System_Guides/raw/main/EInk_Bonnet_Weather_Station/meteocons.ttf
        - name: code.py
          url: https://raw.githubusercontent.com/adafruit/Adafruit_Learning_System_Guides/main/EInk_Bonnet_Weather_Station/code.py
        - name: weather_graphics.py
          url: https://raw.githubusercontent.com/adafruit/Adafruit_Learning_System_Guides/main/EInk_Bonnet_Weather_Station/weather_graphics.py

    # TODO: Replace API key
    # TODO: Replace location (city/state)