galaxy_info:
  author: 1f618
  description: CircuitPython on Linux

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: MIT

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags: 
    - pi
    - raspberry
    - raspbian

dependencies:
  - role: geerlingguy.pip