---
# tasks file for 1f618.circuitpython_on_linux
#
# Installs CircuitPython, based on the following guide:
# https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi

- name: Install pip packages 
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: setuptools
      - name: adafruit-python-shell
        # TODO: upgrade?

- name: Download raspi-blinka.py
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/adafruit/Raspberry-Pi-Installer-Scripts/master/raspi-blinka.py
    dest: "{{ blinka_dir }}/raspi-blinka.py"

- name: Run raspi-blinka.py
  command: python3 raspi-blinka.py
    chdir: "{{ blinka_dir }}"
  become: yes

- name: Copy blinkatest.py
  copy:
    src: blinkatest.py
    dest: "{{ blinka_dir }}/blinkatest.py"

- name: Run blinkatest.py
  command: 'python3 blinkatest.py > blinkatest-output.txt'
    chdir: "{{ blinka_dir }}"

# TODO: reboot (after raspi-blinka.py is done)
