---
# tasks file for 1f618.circuitpython_on_linux
#
# Installs CircuitPython, based on the following guide:
# https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi

- name: Install pip packages 
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: setuptools
      - name: adafruit-python-shell
        # TODO: upgrade?

- name: "Create {{ blinka_dir }} directory"
  ansible.builtin.file:
    path: "{{ blinka_dir }}"
    state: directory

- name: Install Blinka (if necessary)
  block:  
    - name: Check Blinka
      # Run blinkatest.py, to see if Blinka is already configured.
      include_tasks: check_blinka.yml
  rescue:
    - name: Install Blinka
      include_tasks: install_blinka.yml
