---
# tasks file for 1f618.circuitpython_on_linux
#
# Installs CircuitPython, based on the following guide:
# https://learn.adafruit.com/circuitpython-on-raspberrypi-linux/installing-circuitpython-on-raspberry-pi

- name: Install pip packages 
  ansible.builtin.include_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: setuptools
      - name: adafruit-python-shell
        # TODO: upgrade?

- name: "Create {{ blinka_dir }} directory"
  ansible.builtin.file:
    path: "{{ blinka_dir }}"
    state: directory

# Check for an existing successful output first.
# If Blinka is already installed, no need to reinstall.
- name: Check for successful blinkatest-output.log
  # https://stackoverflow.com/questions/30786263/only-check-whether-a-line-present-in-a-file-ansible
  lineinfile:
    name: "{{ blinka_dir }}/blinkatest-output.log"
    line: "{{ item }}"
    state: present
  with_items:
    - 'Digital IO ok!'
    - 'I2C ok!'
    - 'SPI ok!'
  check_mode: yes
  register: conf
  ignore_errors: yes
  notify: Install blinka

# Make sure that `Install blinka` runs (if needed).
- name: Flush handlers
  meta: flush_handlers

# Do a final test, and fail if not successful this time.
- name: Confirm that test output was good
  # https://stackoverflow.com/questions/30786263/only-check-whether-a-line-present-in-a-file-ansible
  lineinfile:
    name: "{{ blinka_dir }}/blinkatest-output.log"
    line: "{{ item }}"
    state: present
  with_items:
    - 'Digital IO ok!'
    - 'I2C ok!'
    - 'SPI ok!'
  check_mode: yes
  register: conf
  failed_when: (conf is changed) or (conf is failed)
